# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: kranthi.maganti1306@gmail.com
author_name: Kranthi Maganti
cloud_provider: netlify
contract_name: carbonfootprint
deployment_language: python
preset_name: production
project_name: carbonfootprint

